### ISSUE TITLE
記事の要望

### ISSUE THREAD

**Issue by baronTommy** [aloerina01/aloerina01.github.io#18]
## `graphql`

`graphql`の堅牢さが気になって使おうとしてます。
https://github.com/graphql/graphiql で基本的な動作は、確認したので、

今は下記記事を参考に、mockを準備しようとしています 
> `json-server` からのりかえたい

- https://qiita.com/mizchi/items/c078aea032cd00ba3e86
- https://www.apollographql.com/docs/graphql-tools/mocking.html
- https://ushumpei.hatenablog.com/entry/2017/12/12/000000

**Comment by baronTommy** [comment]
他の記事が良かったので要望してみました (すみません
重荷だったりしたらcloseで大丈夫ですので

![猫](http://cat.petpetnx.com/img/snapcrab_noname_2016-3-23_19-5-23_no-00.jpg)

**Comment by baronTommy** [comment]
自分なりに書いてしまいました...

https://qiita.com/tommyQiita/items/76df557cb24990a74a80

**Comment by aloerina01** [comment]
ステキです！勉強になりました。参考にして試してみます！

**Comment by baronTommy** [comment]
@aloerina01 
一端closeしますね
バタバタすみませんです
